//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientShared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RealTimeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RealTimeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientShared.Resources.RealTimeMessages", typeof(RealTimeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_ADD_NEW_CATEGORY.
        /// </summary>
        public static string AddNewCategoryContent {
            get {
                return ResourceManager.GetString("AddNewCategoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_ADD_NEW_CATEGORY_GROUP.
        /// </summary>
        public static string AddNewCategoryGroupContent {
            get {
                return ResourceManager.GetString("AddNewCategoryGroupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE_NEW_CATEGORY_GROUP.
        /// </summary>
        public static string AddNewCategoryGroupTitle {
            get {
                return ResourceManager.GetString("AddNewCategoryGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE_NEW_CATEGORY.
        /// </summary>
        public static string AddNewCategoryTitle {
            get {
                return ResourceManager.GetString("AddNewCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_ADD_TOPIC.
        /// </summary>
        public static string AddTopic {
            get {
                return ResourceManager.GetString("AddTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_DELETE_TOPIC.
        /// </summary>
        public static string DeleteTopicContent {
            get {
                return ResourceManager.GetString("DeleteTopicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE_DELETE_TOPIC.
        /// </summary>
        public static string DeleteTopicTitle {
            get {
                return ResourceManager.GetString("DeleteTopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_EDIT_CATEGORY.
        /// </summary>
        public static string EditCategoryContent {
            get {
                return ResourceManager.GetString("EditCategoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_EDIT_CATEGORY_GROUP.
        /// </summary>
        public static string EditCategoryGroupContent {
            get {
                return ResourceManager.GetString("EditCategoryGroupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE_EDIT_CATEGORY_GROUP.
        /// </summary>
        public static string EditCategoryGroupTitle {
            get {
                return ResourceManager.GetString("EditCategoryGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE_EDIT_CATEGORY.
        /// </summary>
        public static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_EDIT_TOPIC.
        /// </summary>
        public static string EditTopic {
            get {
                return ResourceManager.GetString("EditTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG_EDIT_USER_STATUS.
        /// </summary>
        public static string EditUserStatusContent {
            get {
                return ResourceManager.GetString("EditUserStatusContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE_EDIT_USER_STATUS.
        /// </summary>
        public static string EditUserStatusTitle {
            get {
                return ResourceManager.GetString("EditUserStatusTitle", resourceCulture);
            }
        }
    }
}
